EAT-SSU/Server

src/main/java/ssu/eatssu/config/SecurityConfig.java, src/main/java/ssu/eatssu/domain/repository/UserRepository.java, src/main/java/ssu/eatssu/web/user/UserController.java
=> Feat: 닉네임 중복 체크 API

src/main/java/ssu/eatssu/web/user/UserController.java
기존: ResponseEntity
변경: BaseResponse
=> Refactor: 닉네임 중복 성공시 Response type 변경

src/main/java/ssu/eatssu/domain/Menu.java, src/main/java/ssu/eatssu/domain/repository/MenuRepository.java, src/main/java/ssu/eatssu/domain/repository/ReviewRepository.java, src/main/java/ssu/eatssu/service/RefreshingService.java, src/main/java/ssu/eatssu/web/review/ReviewController.java
리뷰 갯수, 평균 별점을 다시 계산하는 API 추가
Solved: #11
=> Hotfix: 리뷰 갯수, 평균 별점이 안맞았던 버그 해결

src/main/java/ssu/eatssu/config/SecurityConfig.java, src/main/java/ssu/eatssu/response/BaseResponseStatus.java, src/main/java/ssu/eatssu/service/MenuService.java, src/main/java/ssu/eatssu/web/restaurant/MenuController.java, src/main/java/ssu/eatssu/web/restaurant/dto/MenuResDto.java, src/main/java/ssu/eatssu/web/user/UserController.java
solved: #7
Refactor: 닉네임 중복 체크 API, 이메일 중복 체크 API
기존: 중복일 경우 true 반환
변경: 중복일 경우 errorcode 반환
=> Feat: mealId로 해당 식단 메뉴들의 menuId, name 리스트 조회

src/main/java/ssu/eatssu/domain/User.java, src/main/java/ssu/eatssu/service/OauthService.java
=> Feat: 이메일 숨기기 옵션으로 애플로그인 시도할 경우 처리

src/main/java/ssu/eatssu/domain/enums/MenuTypeGroup.java, src/main/java/ssu/eatssu/domain/enums/RestaurantName.java
DOMITORY -> DORMITORY
Solved: #24
=> Hotfix: 기숙사 철자 오류 수정

src/main/java/ssu/eatssu/domain/Meal.java, src/main/java/ssu/eatssu/service/RefreshingService.java, src/main/java/ssu/eatssu/service/ReviewService.java, src/main/java/ssu/eatssu/web/review/ReviewController.java
변동메뉴는 mealId 사용으로 다시 변경
식단기준 리뷰 조회시 평점 계산하는 로직 변경
Solved: #23
=> Fix: 리뷰 조회, 삭제 로직 수정

src/main/java/ssu/eatssu/service/ReportService.java, src/main/java/ssu/eatssu/slack/SlackChannel.java, src/main/java/ssu/eatssu/slack/SlackService.java, src/main/java/ssu/eatssu/web/report/ReportController.java
신고가 접수되면 슬랙의 #신고 채널에 알림 전송
solved: #12
=> Feat: 신고 접수 시 슬랙봇 알림

src/main/java/ssu/eatssu/web/user/UserController.java
BaseResponse -> ResponseEntity
solved: #31
=> Hotfix: BaseResponse 사용된 곳 수정

src/main/java/ssu/eatssu/web/user/UserController.java
기존: body값 X
수정 후: body에 boolean return
=> Fix: 이메일 체크, 닉네임 체크, 탈퇴하기 API 사용 시 body값에 boolean사용

src/main/java/ssu/eatssu/web/user/UserController.java
=> Fix: BaseResponse 사용한 부분 변경

src/main/java/ssu/eatssu/domain/Menu.java
리뷰삭제 후 리뷰 갯수가 0일 경우 별점을 0으로 수정
#39
=> Hotfix: 리뷰 삭제후 리뷰 별점 오류 수정

src/main/java/ssu/eatssu/EatSsuApplication.java, src/main/java/ssu/eatssu/service/MenuService.java, src/main/java/ssu/eatssu/web/restaurant/MenuController.java
=> Cancel "Revert "Feat/swagger""

src/main/java/ssu/eatssu/web/mypage/MyPageController.java, src/main/java/ssu/eatssu/web/oauth/OauthController.java, src/main/java/ssu/eatssu/web/report/ReportController.java, src/main/java/ssu/eatssu/web/restaurant/MenuController.java, src/main/java/ssu/eatssu/web/restaurant/RestaurantController.java, src/main/java/ssu/eatssu/web/review/ReviewController.java, src/main/java/ssu/eatssu/web/user/UserController.java
ResponseEntity -> BaseResponse
#43
=> Feat: Response 형식 변경

src/main/java/ssu/eatssu/domain/UserInquiries.java, src/main/java/ssu/eatssu/service/UserService.java
=> Hotfix: 작성한 신고가 있을 경우 탈퇴가 안되는 오류

src/main/java/ssu/eatssu/domain/Menu.java
TasteGrade 평균 오류 수정 (오타때문이었음)
Solved: #56
=> Hotfix: TasteGrade 평균값 오류 수정

src/main/java/ssu/eatssu/config/OpenApiConfig.java
=> Feat: Swagger Server 설정

src/main/java/ssu/eatssu/web/mypage/MyPageController.java, src/main/java/ssu/eatssu/web/oauth/OauthController.java, src/main/java/ssu/eatssu/web/report/ReportController.java, src/main/java/ssu/eatssu/web/restaurant/MenuController.java, src/main/java/ssu/eatssu/web/restaurant/RestaurantController.java, src/main/java/ssu/eatssu/web/review/ReviewController.java, src/main/java/ssu/eatssu/web/user/UserController.java
ResponseEntity -> BaseResponse
=> Feat: BaseResponse 적용

src/main/java/ssu/eatssu/web/mypage/MyPageController.java, src/main/java/ssu/eatssu/web/report/ReportController.java, src/main/java/ssu/eatssu/web/restaurant/MenuController.java, src/main/java/ssu/eatssu/web/restaurant/RestaurantController.java, src/main/java/ssu/eatssu/web/review/ReviewController.java, src/main/java/ssu/eatssu/web/user/UserController.java, src/main/java/ssu/eatssu/web/user_inquiries/UserInquiriesController.java
- Controller 주석 설명을 더 상세하게 추가함
=> Comment: Controller 주석 수정 및 추가

src/main/java/ssu/eatssu/service/MenuService.java, src/main/java/ssu/eatssu/service/MyPageService.java, src/main/java/ssu/eatssu/service/OauthService.java, src/main/java/ssu/eatssu/service/RefreshingService.java, src/main/java/ssu/eatssu/service/ReportService.java, src/main/java/ssu/eatssu/service/ReviewService.java, src/main/java/ssu/eatssu/service/UserInquiriesService.java, src/main/java/ssu/eatssu/service/UserService.java, src/main/java/ssu/eatssu/web/menu/MenuController.java, src/main/java/ssu/eatssu/web/mypage/MyPageController.java, src/main/java/ssu/eatssu/web/oauth/OauthController.java, src/main/java/ssu/eatssu/web/report/ReportController.java, src/main/java/ssu/eatssu/web/review/ReviewController.java, src/main/java/ssu/eatssu/web/user/UserController.java, src/main/java/ssu/eatssu/web/user_inquiries/UserInquiriesController.java
Controller
- HTTP GET 요청을 처리하는 메서드의 네이밍 규칙 : get{XXX}
- HTTP POST 요청을 처리하는 메서드의 네이밍 규칙 
- 리소스 추가 액션 : add{XXX} 
- 작성 액션 : write{XXX}
- HTTP PUT 요청을 처리하는 메서드의 네이밍 규칙 : update{XXX}
- HTTP DELETE 요청을 처리하는 메서드의 네이밍 규칙 : delete{XXX}
=> Refactor: 메소드명 수정 및 주석 보충

src/main/java/ssu/eatssu/jwt/JwtTokenProvider.java, src/main/java/ssu/eatssu/web/menu/MenuController.java, src/main/java/ssu/eatssu/web/mypage/MyPageController.java, src/main/java/ssu/eatssu/web/oauth/OauthController.java, src/main/java/ssu/eatssu/web/report/ReportController.java, src/main/java/ssu/eatssu/web/review/ReviewController.java, src/main/java/ssu/eatssu/web/user/UserController.java, src/main/java/ssu/eatssu/web/userinquiry/UserInquiryController.java
일반적인 오류는 표기 안 했음(파라미터 누락, 타입 오류 등등)
spring swagger 같은 코드 여러 에러 응답 예시 만들기 >> https://devnm.tistory.com/29 적용 고민 ing  . . .
=> Feat: Swagger description 보충 및 ApiResponse 추가

src/main/java/ssu/eatssu/config/SecurityConfig.java, src/main/java/ssu/eatssu/handler/JwtAccessDeniedHandler.java, src/main/java/ssu/eatssu/handler/JwtAuthenticationEntryPoint.java, src/main/java/ssu/eatssu/handler/response/BaseResponseStatus.java, src/main/java/ssu/eatssu/jwt/JwtAuthenticationFilter.java, src/main/java/ssu/eatssu/jwt/JwtTokenProvider.java, src/main/java/ssu/eatssu/web/user/UserController.java
=> Feat: SecurityFilter Layer 에서 발생하는 401, 403 Error Response 커스텀

src/main/generated/ssu/eatssu/domain/QUser.java, src/main/java/ssu/eatssu/domain/User.java, src/main/java/ssu/eatssu/jwt/JwtTokenProvider.java, src/main/java/ssu/eatssu/security/CustomUserDetails.java, src/main/java/ssu/eatssu/security/CustomUserDetailsService.java, src/main/java/ssu/eatssu/security/UserPrincipalDto.java, src/main/java/ssu/eatssu/service/OauthService.java, src/main/java/ssu/eatssu/service/UserService.java, src/main/java/ssu/eatssu/web/user/UserController.java
=> Refactor: 자체 회원가입 / 로그인 제거 및 credentials 필드 추가

src/main/java/ssu/eatssu/domain/menu/dto/MealCreateWithPriceRequest.java, src/main/java/ssu/eatssu/domain/menu/dto/MealInformationResponse.java, src/main/java/ssu/eatssu/domain/menu/entity/Meal.java, src/main/java/ssu/eatssu/domain/menu/entity/Menu.java, src/main/java/ssu/eatssu/domain/menu/presentation/MealController.java, src/main/java/ssu/eatssu/domain/menu/service/MenuService.java, src/main/java/ssu/eatssu/domain/menu/util/MenuValidator.java, src/main/java/ssu/eatssu/domain/restaurant/entity/Restaurant.java
Meal 에 price 필드 추가 + 가격을 파라미터로 입력받는 식단추가 API 개발
=> Feat: Meal 에 price 필드 추가 + 가격을 파라미터로 입력받는 식단추가 API 개발

src/main/java/ssu/eatssu/domain/review/dto/ReviewUpdateRequest.java, src/main/java/ssu/eatssu/domain/review/service/ReviewService.java
=> Change: 리뷰 업데이트 request dto 필드명 변경

src/main/java/ssu/eatssu/domain/admin/controller/AuthenticationController.java, src/main/java/ssu/eatssu/domain/admin/controller/ManageCategoryController.java, src/main/java/ssu/eatssu/domain/admin/controller/ManageFixMenuController.java, src/main/java/ssu/eatssu/domain/admin/dto/LoginRequest.java, src/main/java/ssu/eatssu/domain/admin/dto/MenuSection.java, src/main/java/ssu/eatssu/domain/admin/dto/RegisterCategoryRequest.java, src/main/java/ssu/eatssu/domain/admin/persistence/LoadCategoryRepository.java, src/main/java/ssu/eatssu/domain/admin/persistence/LoadFixMenuRepository.java, src/main/java/ssu/eatssu/domain/admin/persistence/ManageCategoryRepository.java, src/main/java/ssu/eatssu/domain/admin/service/AuthenticationService.java, src/main/java/ssu/eatssu/domain/admin/service/ManageCategoryService.java, src/main/java/ssu/eatssu/domain/admin/service/ManageFixMenuService.java, src/main/java/ssu/eatssu/domain/auth/infrastructure/SecurityConfig.java, src/main/java/ssu/eatssu/domain/menu/entity/Menu.java
[수정사항]
-  고정 메뉴 식당 조회 시 categoryId 필드 추가
- 로그인 시 아이디, 비밀번호 모두 입력 받음
=> Admin 카테고리 및 로그인 관련 수정

.github/README.md
- iOS에 있는 리드미에서 앱 설명에 관한 부분은 설명이 잘 적혀있어서 해당 부분 우선 가져왔습니다.
=> [Docs] README에 기초적인 문서 작성

src/main/java/ssu/eatssu/global/config/QueryDslConfig.java
QueryDslConfig의 패키지 경로를 수정하였습니다.
=> [Fix] QueryDslConfig 파일의 패키지 경로 수정

src/main/java/ssu/eatssu/global/config/S3Config.java
=> fix: 잘못된 패키지 경로 수정

src/main/java/ssu/eatssu/domain/user/dto/DepartmentResponse.java, src/main/java/ssu/eatssu/domain/user/presentation/UserController.java, src/main/java/ssu/eatssu/domain/user/service/UserService.java
- 학과 기입 여부 체크 & 조회 API를 구현했습니다. 업데이트된 API 명세를 참고해주세요. ref. [API 명세](https://www.notion.so/hi-jin-1514/API-19c9b2ff4b1180559c0bea27251a4b99?pvs=4)
=> feat: 학과 기입 여부 체크 & 조회 API 구현

.junie/guidelines.md, Dockerfile, src/main/java/ssu/eatssu/domain/menu/persistence/MealMenuQueryRepository.java, src/main/java/ssu/eatssu/domain/menu/persistence/QuerydslMealRatingCalculator.java, src/main/java/ssu/eatssu/domain/menu/persistence/QuerydslMealRatingCounter.java
- [junie](https://www.jetbrains.com/junie/)를 로컬에서 사용하고 있는데, 더 쉽게 이해할 수 있도록 가이드 라인을 작성했습니다.
- 해당 가이드라인 역시 junie가 수행한 결과물이긴 합니다.
=> docs: Junie 가이드라인 작성

src/main/java/ssu/eatssu/domain/auth/dto/ValidRequest.java, src/main/java/ssu/eatssu/domain/auth/presentation/OAuthController.java, src/main/java/ssu/eatssu/domain/auth/security/JwtTokenProvider.java, src/main/java/ssu/eatssu/domain/auth/service/OAuthService.java, src/test/java/ssu/eatssu/domain/auth/service/OauthServiceTest.java
- #141 
- 토큰 유효성 검사 API를 작성하였습니다.
- OauthServiceTest를 통합테스트에서 단위테스트로 일괄변경하였습니다.
=> feat: 토큰 유효성 검사 API 개발

src/main/java/ssu/eatssu/domain/auth/presentation/OAuthController.java, src/main/java/ssu/eatssu/global/runner/WarmUpRunner.java
- #145 
- JIT 컴파일러의 장점인 캐싱기능을 사용하기 위해 Warmup 코드를 추가하였습니다.
- Application Runner라는 스프링 내부 API를 사용하였습니다.
=> feat: 로그인시 Warmup Runner추가

build.gradle, src/main/java/ssu/eatssu/domain/auth/infrastructure/SecurityConfig.java
- #147 
- actuator, 프로메테우스 의존성 추가
- yml actuator 커스텀해서 변경
- ec2보안그룹 포트 추가
=> feat:  모니터링 의존성 추가, management 추가

src/main/java/ssu/eatssu/domain/menu/persistence/MealMenuRepository.java, src/main/java/ssu/eatssu/domain/review/dto/MealReviewsV2Response.java, src/main/java/ssu/eatssu/domain/review/dto/MenuReviewsV2Response.java, src/main/java/ssu/eatssu/domain/review/presentation/ReviewControllerV2.java, src/main/java/ssu/eatssu/domain/review/repository/ReviewRepository.java, src/main/java/ssu/eatssu/domain/review/service/MealReviewService.java, src/main/java/ssu/eatssu/domain/review/service/ReviewServiceV2.java, src/main/java/ssu/eatssu/domain/user/presentation/UserController.java
- #153
- 기존 review v2 API 실행시, NPE 로 500 에러 나오는 문제 수정
- 하기 노션 링크에 명시된 신규 기획 사항 반영 (좋아요,싫어요 개수 조회되게)
https://www.notion.so/eat-ssu/api-1d2eeef75a16816fade3df057ee82418?source=copy_link
=> Fix/#153 리뷰v2수정

.cursor/rules/eatssu-server-rule.mdc, .github/copilot-instructions.md, .gitignore, CLAUDE.md, GEMINI.md
- .gitignore에서 불필요한 항목 제거
- GEMINI.md 파일 추가하여 응답 규칙 명시
- eatssu-server-rule.mdc 파일 추가하여 라이브러리 임포트 규칙 설정
- copilot-instructions.md 파일 추가
- 잘 쓰실지 안 쓰실지 모르겠지만, 그래도 쓰는 경우에 있는 상황을 고려해서 미리 프로젝트에 반영해두는 것이 적절할 것 같더라구요.
- `GEMINI.md` 파일은 어제 나온 [Gemini CLI](https://github.com/google-gemini/gemini-cli)를 사용하는 상황에 `pre-prompting`으로 사용할 수 있는 규칙들을 작성해두었습니다. 커서랑 깃허브 코파일럿은 크게 언급하지 않아도 아실 것 같구요!
- 추후에 [Claude Code](https://www.anthropic.com/claude-code)와 [OpenAI Codex CLI](https://github.com/openai/codex)도 사용하면서 규칙 파일이 생기면 반영해두겠습니다. (있는데 제가 아직 못 찾은 것 같기도 해요!)
=> feat: .gitignore 및 코드컨벤션에 맞는 AI Rules 작성

src/main/java/ssu/eatssu/domain/review/entity/Review.java
- 리뷰 컨텐츠의 저장 크기가 255자로 제한이 있었더라구요. 이걸 300자로 수정했습니다.
=> feat: Review 엔티티 필드 및 메서드 정리

src/main/java/ssu/eatssu/domain/menu/entity/Menu.java, src/main/java/ssu/eatssu/domain/review/dto/CreateMealReviewRequest.java, src/main/java/ssu/eatssu/domain/review/dto/CreateMenuReviewRequest.java, src/main/java/ssu/eatssu/domain/review/dto/MealReviewResponse.java, src/main/java/ssu/eatssu/domain/review/dto/MealReviewsV2Response.java, src/main/java/ssu/eatssu/domain/review/dto/MenuReviewsV2Response.java, src/main/java/ssu/eatssu/domain/review/dto/ValidMenuForViewResponse.java, src/main/java/ssu/eatssu/domain/review/entity/Review.java, src/main/java/ssu/eatssu/domain/review/presentation/ReviewControllerV2.java, src/main/java/ssu/eatssu/domain/review/service/ReviewServiceV2.java, src/main/java/ssu/eatssu/domain/review/utils/MenuFilterUtil.java, src/main/java/ssu/eatssu/domain/user/dto/MyMealReviewResponse.java
- #174 
- 싫어요 기능 삭제
- 칩: 좋아요한 메뉴 칩, 전체 메뉴 칩 필드 추가
- 리뷰에서 제외되는 메뉴 api 추가 (/v2/reviews/meal/valid-for-review/{mealId} 참고)
- 단일메뉴 리뷰 작성시 좋아요 기능 추가
=> feat: 250626 리뷰v2수정요청사항

src/main/java/ssu/eatssu/domain/auth/infrastructure/SecurityConfig.java, src/main/java/ssu/eatssu/domain/auth/security/JwtAuthenticationFilter.java, src/main/java/ssu/eatssu/domain/auth/security/JwtTokenProvider.java, src/main/java/ssu/eatssu/domain/menu/entity/Meal.java, src/main/java/ssu/eatssu/domain/menu/entity/Menu.java, src/main/java/ssu/eatssu/domain/partnership/dto/CreatePartnershipRequest.java, src/main/java/ssu/eatssu/domain/partnership/presentation/PartnershipController.java, src/main/java/ssu/eatssu/domain/partnership/service/PartnershipService.java, src/main/java/ssu/eatssu/domain/review/dto/ValidMenuForViewResponse.java, src/main/java/ssu/eatssu/domain/review/presentation/ReviewControllerV2.java, src/main/java/ssu/eatssu/domain/slack/entity/SlackMessageFormat.java, src/main/java/ssu/eatssu/domain/slack/service/SlackErrorNotifier.java, src/main/java/ssu/eatssu/domain/user/department/entity/College.java, src/main/java/ssu/eatssu/domain/user/department/entity/Department.java, src/main/java/ssu/eatssu/domain/user/entity/User.java, src/main/java/ssu/eatssu/global/handler/GlobalExceptionHandler.java, src/main/java/ssu/eatssu/global/handler/response/BaseResponseStatus.java, src/main/resources/application-local.yml
- #194 
- 시큐리티 필터에서도 슬랙 알림 전송
- 슬랙 알림 클래스 별도로 만들어서, filter에 의존성 주입할수 있게 변경
- 기존 filterChain의 doFilter메서드에서 whitelist 관련 처리 미비한 부분 수정
=> fix: 시큐리티 필터에서도 슬랙 알림 보낼 수 있게 수정

.gemini/styleguide.md, .gitignore, src/main/resources/application.yml, src/test/resources/application.yml
- 다양한 프로젝트를 하다보니 모든 환경변수를 OS에 보관하기에 복잡도가 너무 올라갔습니다. 그래서 이것을 프로젝트 별로 하는 것으로 방식을 바꾸었습니다.
- 예를 들어서 프로젝트 A에서도 OpenAI 토큰을 쓰고 프로젝트 B에서도 OpenAI 토큰을 쓰는데 이것을 `.bashrc` 파일이나 `.zshrc` 파일에 기록하기에는 동일한 이름의 변수명이라서 이렇게 하는 것보다 프로젝트에 종속시키는 것이 복잡도를 낮출 수 있다고 판단했습니다.
- 사용되는 `.env` 파일은 형식이 좀 다른데요! 
- export와 값에 ""를 제거해야 합니다.
=> feat: .env 파일 사용

src/main/java/ssu/eatssu/domain/restaurant/entity/Restaurant.java
- #203 
- 식단 추가 API에 교직원식당 FACULTY로 enum 추가했습니다. 매우 사소한 수정사항이라 바로 머지할게욤
=> feat: 식단 추가 api에 FACULTY enum추가

build.gradle
- `build.gradle`에 Java 17 명시
- JVM 진짜 새로운 컴퓨터에서 개발환경 구축할 때 마다 이거 세팅하는 것도 일이네요.
- 해당 정보가 누락되어있어서, QueryDSL이 민감하게 영향을 받기 때문에 `build.gradle` 명시를 했다고 기억하고 있는데, 다시 보니까 없더라구요.
=> fix: Java Toolchain 설정 추가 (Java 17)

src/main/java/ssu/eatssu/domain/partnership/persistence/PartnershipRepository.java, src/main/java/ssu/eatssu/domain/partnership/persistence/PartnershipRestaurantRepository.java
- #234 
- 직전 v2.0.7의 쿼리 오류를 해결 합니다.
=> fix: 쿼리 수정

src/main/java/ssu/eatssu/domain/auth/infrastructure/SecurityConfig.java, src/main/java/ssu/eatssu/domain/auth/security/JwtAuthenticationFilter.java, src/main/java/ssu/eatssu/domain/menu/entity/Menu.java, src/main/java/ssu/eatssu/domain/menu/persistence/QuerydslMenuRatingCalculator.java, src/main/java/ssu/eatssu/domain/partnership/dto/PartnershipInfo.java, src/main/java/ssu/eatssu/domain/partnership/entity/Partnership.java, src/main/java/ssu/eatssu/domain/partnership/persistence/PartnershipRepository.java, src/main/java/ssu/eatssu/domain/restaurant/entity/Restaurant.java, src/main/java/ssu/eatssu/domain/review/dto/CreateMenuReviewRequest.java, src/main/java/ssu/eatssu/domain/review/dto/MealReviewResponse.java, src/main/java/ssu/eatssu/domain/review/dto/MealReviewsV2Response.java, src/main/java/ssu/eatssu/domain/review/dto/MenuReviewsV2Response.java, src/main/java/ssu/eatssu/domain/review/dto/RestaurantReviewResponse.java, src/main/java/ssu/eatssu/domain/review/dto/ReviewDetail.java, src/main/java/ssu/eatssu/domain/review/dto/ValidMenuForViewResponse.java, src/main/java/ssu/eatssu/domain/review/service/ReviewServiceV2.java, src/main/java/ssu/eatssu/domain/review/utils/MenuFilterUtil.java, src/main/java/ssu/eatssu/domain/user/department/entity/College.java, src/main/java/ssu/eatssu/domain/user/department/entity/Department.java, src/main/java/ssu/eatssu/domain/user/dto/GetDepartmentResponse.java, src/main/java/ssu/eatssu/domain/user/dto/MyMealReviewResponse.java, src/main/java/ssu/eatssu/domain/user/service/UserService.java, src/main/java/ssu/eatssu/global/handler/GlobalExceptionHandler.java, src/main/java/ssu/eatssu/global/handler/response/BaseResponseStatus.java
- #247 
맛,양 rating null값 나오던 것 
- 유관 api: v2/reviews/list/menu 
- 필드 완전 삭제함
mainRating->rating
- 유관 api : v2/review/statistics/restaurant , v2/review/statistics/menus/{menuId}, v2/review/statistics/meals/{mealId}
스웨거
- json 깨지는 부분들 확인 후 수정함 (리뷰 v2만 우선적으로 싱크 맞춰둠)
=> fix: 250930 수정요청사항

src/main/java/ssu/eatssu/domain/review/dto/CreateMealReviewRequest.java, src/main/java/ssu/eatssu/domain/review/dto/CreateMenuReviewRequest.java, src/main/java/ssu/eatssu/domain/review/presentation/ReviewControllerV2.java
- #255 
- V2 API에서 별점 입력값 범위에 대한 검증 로직을 추가했습니다.
=> fix: V2 리뷰 별점 관련 입력값 검증
